/**
 * Dashboard App authentication — HMAC token validation.
 * Used by all /api/dashboard/* routes (called from Chatwoot Dashboard App iframes).
 *
 * Token format: {agentId}.{expiry_ms}.{hmac}
 *   - agentId:   BFF Agent record ID
 *   - expiry_ms: Unix timestamp in ms (token invalid after this)
 *   - hmac:      HMAC-SHA256(agentId + "." + expiry_ms, INTERNAL_SECRET) as hex
 *
 * Security notes:
 * - timingSafeEqual prevents timing attacks on HMAC comparison
 * - INTERNAL_SECRET never exposed to browser code — only the token output
 * - Tokens generated by OCMT at provisioning time, embedded in Chatwoot Dashboard App URLs
 * - TODO-001: expiry enforced here (1h default, configurable)
 * - TODO-005: tokenVersion check (add when Agent.tokenVersion field exists)
 */

import { createHmac, timingSafeEqual } from 'crypto'
import { NextRequest } from 'next/server'

/** Validate a raw token string — use this in Server Components and API routes alike */
export function validateToken(token: string): string | null {
  const secret = process.env.INTERNAL_SECRET
  if (!secret || !token) return null

  const parts = token.split('.')
  if (parts.length !== 3) return null
  const [agentId, expiryMs, sig] = parts
  if (!agentId || !expiryMs || !sig) return null

  const expiry = parseInt(expiryMs, 10)
  if (isNaN(expiry) || Date.now() > expiry) return null

  const payload = `${agentId}.${expiryMs}`
  const expected = createHmac('sha256', secret).update(payload).digest('hex')

  try {
    const sigBuf = Buffer.from(sig, 'hex')
    const expectedBuf = Buffer.from(expected, 'hex')
    if (sigBuf.length !== expectedBuf.length) return null
    if (!timingSafeEqual(sigBuf, expectedBuf)) return null
  } catch {
    return null
  }

  return agentId
}

export function validateDashboardToken(req: NextRequest): string | null {
  const secret = process.env.INTERNAL_SECRET
  if (!secret) return null

  const token = new URL(req.url).searchParams.get('token')
  if (!token) return null

  const parts = token.split('.')
  if (parts.length !== 3) return null

  const [agentId, expiryMs, sig] = parts

  if (!agentId || !expiryMs || !sig) return null

  // Check expiry (TODO-001)
  const expiry = parseInt(expiryMs, 10)
  if (isNaN(expiry) || Date.now() > expiry) return null

  // Validate HMAC — timing-safe comparison (critical: see pitfall hmac-timing-attack-dashboard-auth)
  const payload = `${agentId}.${expiryMs}`
  const expected = createHmac('sha256', secret).update(payload).digest('hex')

  let sigBuf: Buffer
  let expectedBuf: Buffer
  try {
    sigBuf = Buffer.from(sig, 'hex')
    expectedBuf = Buffer.from(expected, 'hex')
  } catch {
    return null
  }

  if (sigBuf.length !== expectedBuf.length) return null
  if (!timingSafeEqual(sigBuf, expectedBuf)) return null

  return agentId
}

/**
 * Generate a dashboard token (used by OCMT at provisioning time, or admin scripts).
 * expiryMs: token lifetime in milliseconds (default: 1 hour)
 */
export function generateDashboardToken(agentId: string, expiryMs = 3600000): string {
  const secret = process.env.INTERNAL_SECRET
  if (!secret) throw new Error('INTERNAL_SECRET not set')

  const expiry = Date.now() + expiryMs
  const payload = `${agentId}.${expiry}`
  const sig = createHmac('sha256', secret).update(payload).digest('hex')

  return `${agentId}.${expiry}.${sig}`
}
