export const metadata = { title: "Terms of Service — BFF AI" };

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#FAFAFA]/80 px-6 py-16 max-w-3xl mx-auto">
      <h1 className="text-4xl font-extrabold text-white mb-2">Terms of Service</h1>
      <p className="text-sm text-[#A1A1AA] mb-8">Last updated: March 8, 2026</p>

      <div className="space-y-6 leading-relaxed">
        <section>
          <h2 className="text-xl font-bold text-white mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using BFF AI (&quot;the Service&quot;), provided by EPIC Communications Inc. (&quot;we&quot;, &quot;us&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">2. Description of Service</h2>
          <p>BFF AI provides AI-powered personal assistant agents that communicate with you via WhatsApp and our web dashboard. The Service includes AI chat, reminders, bill tracking, to-do management, and other assistant features.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">3. Account Registration</h2>
          <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information and be at least 13 years old to use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc ml-6 mt-2 space-y-1">
            <li>Use the Service for illegal, harmful, or fraudulent purposes</li>
            <li>Send spam, harassment, or unsolicited messages through your agent</li>
            <li>Attempt to reverse-engineer, hack, or compromise the Service</li>
            <li>Impersonate another person or entity</li>
            <li>Use the Service to generate harmful, abusive, or misleading content</li>
            <li>Exceed your plan&apos;s usage limits through automated means</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">5. AI-Generated Content</h2>
          <p>Responses from your AI agent are generated by artificial intelligence and may not always be accurate, complete, or appropriate. You are responsible for reviewing and acting on AI-generated content. We are not liable for decisions made based on AI responses.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">6. Plans & Billing</h2>
          <p>BFF AI offers Free, Pro ($29/mo), and Business ($99/mo) plans. Paid plans are billed monthly. You may cancel at any time; access continues until the end of the billing period. Refunds are provided at our discretion.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">7. WhatsApp Usage</h2>
          <p>By connecting your WhatsApp number, you consent to receiving messages from your AI agent. You can disconnect at any time through your dashboard settings. Message delivery depends on WhatsApp/Meta&apos;s platform and is not guaranteed.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">8. Intellectual Property</h2>
          <p>The Service, including its design, code, and branding, is owned by EPIC Communications Inc. Your data remains yours. By using the Service, you grant us a limited license to process your data solely to provide the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">9. Limitation of Liability</h2>
          <p>THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, EPIC COMMUNICATIONS INC. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">10. Termination</h2>
          <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time. Upon termination, your data will be deleted within 30 days.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">11. Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use after changes constitutes acceptance. We will notify users of material changes via email or in-app notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">12. Governing Law</h2>
          <p>These terms are governed by the laws of the Commonwealth of Dominica.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-white mb-2">13. Contact</h2>
          <p>EPIC Communications Inc.<br/>Roseau, Dominica<br/>Email: <a href="mailto:info@epic.dm" className="text-[#E2725B] hover:underline">info@epic.dm</a><br/>Phone: +1 (767) 285-8382</p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-white/[0.07] text-center text-[#A1A1AA] text-xs">
        <p>© 2026 BFF AI — Powered by EPIC Communications Inc.</p>
      </div>
    </div>
  );
}
